name: Workflow 
on:
  push:
    branches:
      - develop
      - staging
      - main

jobs:

  repository_dispatch:

    runs-on: ubuntu-latest

    steps:
      - name: Get branch names
        id: branch-names
        uses: tj-actions/branch-names@v8
      # Verificar la rama   
      - name: Get Ref brach name
        run: |
          if [[ "${{ steps.branch-names.outputs.ref_branch }}" == "develop" ]]; then
            echo "env=dev" >> $GITHUB_ENV
          elif [[ "${{ steps.branch-names.outputs.ref_branch }}" == "staging" ]]; then
            echo "env=stg" >> $GITHUB_ENV
          else [[ "${{ steps.branch-names.outputs.ref_branch }}" == "main" ]]; then
            echo "env=prod" >> $GITHUB_ENV
          fi

      - uses: peter-evans/repository-dispatch@v3
        with:
           token: ${{ secrets.REPO_ACCESS_TOKEN }}
           repository: SD-MS-DevOps/IaC-DevOps
           event-type: ms-service
           client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "repository": "${{ github.repository }}"}'